### ISSUE TITLE
Some pages are loading slowly

### ISSUE THREAD

**Issue by michaelcpuckett** [michaelcpuckett/ap-groups#16]
Traffic has increased so I need to look into performance tuning.

**Comment by michaelcpuckett** [comment]
Note: Turning on Cloudflare breaks the server, because HTML/JSON pages get mixed up

**Comment by dakkar** [comment]
Cloudflare is also returning 403 for webfinger queries from my instance _and_ my home connection…

I suspect that it gets very confused by non-browsers sending requests

**Comment by michaelcpuckett** [comment]
Thanks for letting me know! I just turned off Cloudflare for webfinger

I was getting a ton of requests, so I might have to figure out an alternate solution

**Comment by dakkar** [comment]
`curl -v -H 'Accept: application/ld+json' 'https://chirp.social/.well-known/webfinger?resource=acct:perl@chrip.social'` still 403 from here 😕

a header says:
```
report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=9PgUA%2FoXymOv8f6L4lXi149mAUHRjFHdNns2lAvj%2FtGBrtJnSmHprK7APhjgGOfFWr6Gp0mbkEgdsMoLfoUb8UmmuO3ov8k7cnEE2Xfmyo8omiiTD8jjQHM5VIusJA%3D%3D"}],"group":"cf-nel","max_age":604800}
```
if it helps any

I appreciate that running a popular fedi node is a pain!

**Comment by michaelcpuckett** [comment]
@dakkar That's interesting -- I got the same thing when curling but updated some configuration settings in Cloudflare.

Would you mind to try again?

**Comment by michaelcpuckett** [comment]
@dakkar Oh also that will give you an XML version... There is no ld+json version, only application/json and application/jrd+application

**Comment by dakkar** [comment]
ah! I'm not sure what mimetypes my Misskey instance asks for, but it works now!

Thanks you for the very quick response!

**Comment by michaelcpuckett** [comment]
Traffic has reduced and this is less of an issue now.

Just noting that Cloudflare isn't really helpful in this case (due to the vary header). May need to look into alternate solutions

**Comment by michaelcpuckett** [comment]
This was a different problem today actually! The site should be working again. 😅
