### ISSUE TITLE
Delete button not working

### ISSUE THREAD

**Issue by lckrohjr** [michaelcpuckett/ap-groups#19]
Delete button not working.

Once signed in, there is an option to delete a group. The button with this function does not seem to do anything. 
![Screenshot 2022-12-14 121839](https://user-images.githubusercontent.com/49791021/207663396-327d6a56-c455-4716-b558-a26f6adf0a4b.png)

**Comment by michaelcpuckett** [comment]
@lckrohjr Thank you for trying chirp.social !

The code should be fixed the button will now delete the group.

It will send you back to the login page.

The directory may take an hour or so to update before it no longer shows the group.

Right now the site is extremely slow so you might have to wait a minute or two to log in and delete it.

Sorry about this!

**Comment by michaelcpuckett** [comment]
Please let me know if you still have an issue, thanks!
