### ISSUE TITLE
Add Forgot/Reset Password

### ISSUE THREAD

**Issue by michaelcpuckett** [michaelcpuckett/ap-groups#2]
Firebase is signaling to some users via JS console to reset the password, but there is no way to do that currently.

Forgot password is also a useful feature.

**Comment by jernst** [comment]
Here's the output that's printed on the console now. It first said wrong password but went over to "too many" quickly.

```
FirebaseError: Firebase: Access to this account has been temporarily disabled due to many failed login attempts. You can immediately restore it by resetting your password or you can try again later. (auth/too-many-requests).
    Xe subscribe.ts:170
    create subscribe.ts:211
    br navigator.ts:55
    Mr token.ts:61
    $r reload.ts:67
    Ur token.ts:77
    _getIdTokenResponse mfa_error.ts:62
    _getIdTokenResponse mfa_info.ts:61
    Fn recaptcha_verifier.ts:274
    Vn resolver.ts:35
    Bn idp.ts:66
    Wn auth_event_manager.ts:37
    value login-form.ts:58
    handleEvent lit-html.ts:2003
[login-form.ts:64:14](https://chirp.social/components/login-form.ts)
​```

**Comment by michaelcpuckett** [comment]
Thanks for the extra context @jernst and reporting it originally!

I hope you are able to access your account now. Please let me know if you still have any trouble.

I have added "Forgot Password" flow to the homepage and login page.

I'm going to leave this open for a couple of days until I verify the chirp.social domain with Firebase's automated email system.

**Comment by michaelcpuckett** [comment]
Will come back to this when implementing passport.js
