### ISSUE TITLE
Edited posts appear as duplicates in dashboard

### ISSUE THREAD

**Issue by Andre601** [michaelcpuckett/ap-groups#20]
A post I've made and later edited appears multiple times in the dashboard. They seem to be counted as "reposts", which would be wrong.

I think edits should be listed. Just not as a separate entry.

The issue I'm referring to:
![grafik](https://user-images.githubusercontent.com/11576465/207902309-61eecbdc-6e99-4efa-8251-8d53a36bb8c5.png)

**Comment by michaelcpuckett** [comment]
The auto-reposting code is only ever a side effect of an incoming "Create" (not "Update")

When the chirp server sends out a repost, it sends it out to all the servers that follow the account. Then typically those servers will forward the activity back to chirp... I protect against that getting processed again.

But other servers may also send the same original repost to the chirp server, which I was not protecting against.

**Comment by michaelcpuckett** [comment]
Closing but please let me know if the issue persists @Andre601

**Comment by michaelcpuckett** [comment]
Still seeing this but not sure the reason why, reopening

**Comment by michaelcpuckett** [comment]
I pushed what I think will fix this (checking the object ID), but it's hard to detect when it happens, so we'll see!

**Comment by michaelcpuckett** [comment]
I think these were replies that weren't being shown. Pushed what I think will fix it this time (hopefully!)

**Comment by michaelcpuckett** [comment]
Should be fixed now but keeping an eye on it
