### ISSUE TITLE
Hide content, avatars, etc from unsafe groups

### ISSUE THREAD

**Issue by Andre601** [michaelcpuckett/ap-groups#22]
There seem to be groups on chirp.social that aren't SFW, such as porn focused groups.

Idk if you tolerate those or don't want those on it, but if you do want to allow, then at least make it mandatory to mark it as nsfw and hide avatars and alike from being shown.

I say this because there is at least one such group and images and posts aren't behind a CW, which can be really bad if minors stumble upon it.

It would probably better to disallow NSFW in general but this is something up to you to decide.

**Comment by michaelcpuckett** [comment]
@Andre601 Hi! Good point about minors. This is an important issue...

I put a NSFW/sensitive flag to the profile page that people can opt in to. For the ones that had "porn" in the name I went ahead and added that flag.

Closing the issue, but please let me know if you have any other thoughts!
