### ISSUE TITLE
Better Profile description support.

### ISSUE THREAD

**Issue by Andre601** [michaelcpuckett/ap-groups#27]
I've noticed the following issues and/or inconveniences in relation to the profile viewed from a Mastodon client:

- Profile description doesn't have line breaks
- Hashtags and user mentions aren't clickable

It would be nice if those issues could be fixed.
Also, Idk if that is doable with the info boxes Mastodon provides, but perhaps allow newlines there too?

**Comment by michaelcpuckett** [comment]
Hi @Andre601 ! Thanks for this suggestion.

I've implemented all this except user mentions in the bio, however the group manager field does become clickable if you add your @username@domain (I think this should suffice for now).

As part of this, I've also changed the organization of the directory part of the site to be based on hashtags.

Closing, but if you have any thoughts or feedback, please let me know!
