### ISSUE TITLE
Follow requests displayed as "Request not found" and is impossible to vet

### ISSUE THREAD

**Issue by ienzo** [michaelcpuckett/ap-groups#30]
![image](https://user-images.githubusercontent.com/4653894/210363796-a4316d59-7c89-474c-9e93-34fb07fa2ea2.png)

Here is how it looks like on chirp.social.

**Comment by michaelcpuckett** [comment]
Hi @ienzo thanks for reporting this!

It should be fixed now. Please let me know if you see any other issues.

**Comment by ienzo** [comment]
Thanks! It works now.
