### ISSUE TITLE
Feedback on save please

### ISSUE THREAD

**Issue by PythonLinks** [michaelcpuckett/ap-groups#34]
First of all thank you so much for creating this service.  A "moderated email list" is a great idea.  

A tiny point, when I edited my profile and saved it, there was no feedback that it had been saved.  Displaying the message : "Your changes have been saved." would be helpful. 

Also it is not clear to me if this publishes to people's timeline, of it creates direct messages.  It might be good to be able to choose between those two.  Not critical.

**Comment by michaelcpuckett** [comment]
Thanks for the suggestion. I added a simple modal on profile save.
