### ISSUE TITLE
Various questions

### ISSUE THREAD

**Issue by Andre601** [michaelcpuckett/ap-groups#4]
I've read the page, but still have some open questions I hope to get answered.

First things first, I would like to get some clarifications on how the reposting (boosting) works.
The page says to follow the account and "Post a message addressed to it"
Does it mean the message needs to be `@user@chirp.social Hello there!` or would `Hello there @user@chirp.social` also work?
If only the first works, could it be added that the second option (Mention anywhere) would work? From what I've tried does it seem like to ignore the second type which is somewhat limiting.
Perhaps with an option to toggle it could it be added?

Next, will avatars update on pages like Mastodon? Checking the page on the instance I use doesn't show the avatar I've set for it.
Is it on a timer (only checks and updates periodically)? Is it a fediverse behaviour? Not supported?

Thank you in advance for your answers.

**Comment by Andre601** [comment]
Updating the page showed that it did repost my message. Tho I haven't received a Notification about the repost yet, so I can't say if that is just a delay, or if you somehow repost without giving out a notification...

**Comment by Andre601** [comment]
> Yes, it should update throughout the fediverse after you upload an image.

It didn't update yet.
Will check if other instances show it.

**Comment by Andre601** [comment]
Okay, tested a bit arround and so far came to the following conclusions:

- The avatar still isn't rendered on the instance I use when viewing the profile
- Took me quite a bit to test, but other instances seem to display the avatar, so it is most likely an issue with my instance's image handling or smth...
- Still no notification present, so this must be a Mastodon bug, or chirp.social somehow manages to perform actions without any notifications being send out.

**Comment by Andre601** [comment]
Alright, searching for the account on my instance actually forced a loading of the image...

**Comment by Andre601** [comment]
Something I noticed is, that the account displays "14 posts" but only two are present as of writing this.

I'm not too invested into Mastodon so idk how it works exactly... Could those be hidden posts (Unlisted/mention only) or perhaps posts that got deleted later on?

Just a bit confused about this.

**Comment by michaelcpuckett** [comment]
>  the account displays "14 posts" but only two are present 

Right now everything the account does, including a profile update, is counted as a post.

It would be nice if I could control that, I will need to look into it more!

Thanks for sticking with it.

**Comment by michaelcpuckett** [comment]
Closing in favor of #23
