### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by aschrijver** [michaelcpuckett/ap-groups#42]
Hi there. Nice project. The used AP library is MIT-licensed. This project has no license as yet. Would you consider adding an open license to turn the project from 'source available' to open source?

**Comment by ch0ccyra1n** [comment]
I would really like this to happen, especially now that chirp.social is gone

**Comment by Marivaux32** [comment]
It would be great if someone produced something similar--the gup.pe groups have limited functionality (you can't ban someone, it doesn't produce a web archive, etc.)

**Comment by michaelcpuckett** [comment]
@aschrijver -- Sorry, I archived this without realizing it couldn't be forked! Unarchived it.

**Comment by aschrijver** [comment]
Thank you!
