### ISSUE TITLE
Group admins

### ISSUE THREAD

**Issue by majorlinux** [michaelcpuckett/ap-groups#5]
Not sure if this is the place to make suggestions, so let me know if not.

However, if it is, is it possible to add multiple admins to a group?

It would be nice if multiple people were able to admin so it could be more communal in nature when trying to keep spaces safe.

Thanks in advance!

**Comment by michaelcpuckett** [comment]
Hi @majorlinux ! Thanks for trying chirp.social !

That's a great idea. It will take a little bit of time/thinking for how to implement that, because right now one email address = one account.

**Comment by michaelcpuckett** [comment]
@majorlinux Hi again! Thanks again for your suggestion.

I have implemented this with a few caveats:
