### ISSUE TITLE
Creating an account isn't clear

### ISSUE THREAD

**Issue by dmethvin** [michaelcpuckett/ap-groups#7]
On the chirp.social page it says:

## How does this work?
1. Create an account on this page.

There is no "create an account" link. Nothing on that page seems to be related to creating an account.

**Comment by michaelcpuckett** [comment]
@dmethvin Hi thanks for trying chirp.social !

If you happen to be on mobile, it's all the way at the bottom of the page. I should bring it higher up! Thanks for the suggestion.

**Comment by dmethvin** [comment]
I'm on desktop (Windows) and here's the bottom of the page.

<img width="938" alt="Screenshot 2022-12-13 193731" src="https://user-images.githubusercontent.com/157858/207475820-91ddcc39-4a0d-4853-a2e8-ab495027e360.png">

Here's the whole page in PDF.
[chirp-social-page.pdf](https://github.com/michaelcpuckett/ap-groups/files/10223146/chirp-social-page.pdf)

**Comment by michaelcpuckett** [comment]
On desktop, the "Sign Up" form is on the right-hand side of the page.

Sorry for the confusion!

**Comment by dmethvin** [comment]
Ah, so "Create an account" means "Sign up for a group"? I didn't make that connection at all. 

<img width="910" alt="Screenshot 2022-12-14 082549" src="https://user-images.githubusercontent.com/157858/207607525-c399c287-cc99-4933-82a9-3976f4395f09.png">

**Comment by michaelcpuckett** [comment]
Updated the wording on the home page

Thanks again!

**Comment by dmethvin** [comment]
Thank you!
