### ISSUE TITLE
banner does not populate and cannot be set

### ISSUE THREAD

**Issue by CommunistSpectator** [michaelcpuckett/ap-groups#8]
i think that the banner should be uniform for every group: the logo from the upper left of chirp.social. save on server space and help clear up any confusion about the fact that the account is actually a group/bot.

**Comment by CommunistSpectator** [comment]
![chirpBanner](https://user-images.githubusercontent.com/8131102/207212434-4b6c0f8a-698b-4538-b7ab-2bca17507ba3.png)


proposed banner. already the 3:1 that is the default, and content is scaled to sit inside the 5:1 space created on some pages

**Comment by michaelcpuckett** [comment]
HI @CommunistSpectator ! Thanks for trying chirp.social !

I like this idea -- you're saying it's better to have one standardized banner instead of letting people upload their own?

Maybe this could be the default banner and people can upload an additional one if they like? What do you think of that idea?

**Comment by CommunistSpectator** [comment]
i really do think that having the standardized banner, at least while people learn what chirp is, will be helpful to distinguish it. after a year, allowing ppl to change the banner might be ok.

**Comment by michaelcpuckett** [comment]
@CommunistSpectator Thank you so much! I have implemented this for new accounts. There's not a super easy way for me to update old accounts, but I made it so if they update their profile at all, the banner will update to the correct one.

I'm closing this, but please let me know if you see any issue. Thanks again!
